name: CI

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare signing key
        run: echo '${{ secrets.SIGNING_KEY }}' | base64 -d > signingkey.jks

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      - name: Build release binary with Gradle
        uses: gradle/gradle-command-action@v2
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        with:
          arguments: assembleRelease

      - name: Clean up
        run: |
          rm signingkey.jks
          rm -f ${{github.workspace}}/app/build/outputs/apk/release/app-release-unsigned.apk

      - uses: ncipollo/release-action@v1
        with:
          # allowUpdates: true
          artifacts: "${{github.workspace}}/app/build/outputs/apk/release/*.apk"
      
      # Upload to COS
      - uses: git9527/setup-coscli@v2
        with:
          region: ${{ secrets.COS_REGION }}
          secret-id: ${{ secrets.COS_SECRET_ID }}
          secret-key: ${{ secrets.COS_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          coscli-version: 'v0.12.0-beta' # Optional, default to 'v0.12.0-beta'.  Use 'latest' to get the latest version.
      - run: |
          coscli sync ${{github.workspace}}/app/build/outputs/apk/release cos://${{ secrets.COS_BUCKET }} --recursive --thread-num 20